# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSubstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dosage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('FH', 'Forehead'), ('NS', 'Nose'), ('TE', 'Teeth'), ('CH', 'Chest'), ('AR', 'Arm'), ('ST', 'Stomach'), ('RS', 'Rightside'), ('LS', 'Leftside'), ('GR', 'Groin'), ('KN', 'Knees'), ('AK', 'Ankle')], max_length=2)),
                ('intensive', models.CharField(choices=[('T', 'Terrible'), ('M', 'Mild'), ('S', 'Strong'), ('A', 'Average')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('PL', 'Plasters'), ('SP', 'Suppository'), ('PO', 'Powders'), ('TB', 'Granules'), ('OM', 'Ointment'), ('LQ', 'LiquidPrepartions')], max_length=2)),
                ('amountOfSubstance', models.FloatField()),
                ('activeSubstance', models.ManyToManyField(to='MainAnalyz.ActiveSubstance')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(choices=[('FH', 'Forehead'), ('NS', 'Nose'), ('TE', 'Teeth'), ('CH', 'Chest'), ('AR', 'Arm'), ('ST', 'Stomach'), ('RS', 'Rightside'), ('LS', 'Leftside'), ('GR', 'Groin'), ('KN', 'Knees'), ('AK', 'Ankle')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='symptom',
            field=models.ManyToManyField(to='MainAnalyz.Symptom'),
        ),
        migrations.AddField(
            model_name='activesubstance',
            name='sickness',
            field=models.ManyToManyField(to='MainAnalyz.Disease'),
        ),
    ]
