# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MainAnalyz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disease',
            name='intensive',
            field=models.CharField(choices=[('S', 'Strong'), ('T', 'Terrible'), ('A', 'Average'), ('M', 'Mild')], max_length=1),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='type',
            field=models.CharField(choices=[('PO', 'Powders'), ('PL', 'Plasters'), ('LQ', 'LiquidPrepartions'), ('SP', 'Suppository'), ('TB', 'Granules'), ('OM', 'Ointment')], max_length=2),
        ),
    ]
